{% set name = "fs.sshfs" %}
{% set version = "0.7.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.python.org/packages/46/3a/524e282d45936558012db7bf58616f90b278721d3cea3194e4d790f04610/fs.sshfs-0.7.1.tar.gz
  sha256sum: 4669ea1a0b796bc035045570c9efa29fb3cbe9e284e6a177730df6dd08ded340

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - six >=1.10.0,<2
    - paramiko >=2,<3
    - fs >=2.0.7,<2.1
    - configparser  # [py2k]

test:
  imports:
    - fs.sshfs

about:
  home: https://github.com/althonos/fs.sshfs
  license: LGPL v2.1
  summary: 'Pyfilesystem2 over SSH using paramiko'
  description: >
    Once created, the SSHFS filesystem behaves like any other filesystem
    see the Pyfilesystem2 documentation https://pyfilesystem2.readthedocs.io.

extra:
  recipe-maintainers:
    - ReimarBauer
